name: Update ATC Terminology Weekly

on:
  schedule:
    - cron: '0 6 * * 1' # Every Monday at 6:00 UTC
  workflow_dispatch:     # Allow manual trigger
permissions:
  contents: write
jobs:
  update:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gnumeric python3-pip unzip wget

      - name: Download and extract script
        run: |
          wget https://github.com/sarrabenyahia/webscrap_health_monitoring/archive/main.zip
          unzip main.zip

      - name: Install Python requirements
        run: |
          pip3 install -r webscrap_health_monitoring-main/requirements.txt

      - name: Run ATC script
        run: |
          cd webscrap_health_monitoring-main/bs4
          python3 act_ddd_script.py
          ssconvert ATC_DDD_Index.xlsx ATC_DDD_Index.csv
          mv ATC_DDD_Index.csv ../../atc-codesystem.csv
          cd ../..

      - name: Clean up
        run: |
          rm -rf main.zip webscrap_health_monitoring-main

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add atc-codesystem.csv
          git commit -m "Update ATC terminology [automated]" || echo "No changes"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
